import { KeyboardAvoidingView, Platform,StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#dcc1a7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  contentContainer: {
    ...Platform.select({
      ios: {
        marginBottom: 20,
      },
    }),
    marginTop: 50,
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    backgroundColor: '#dcc1a7',
    flexDirection: 'column',
  },
  KeyboardAvoidingView: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    backgroundColor: '#dcc1a7',
    flexDirection: 'column',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  
  modalContent: {
    width: '90%',
    maxHeight: '80%',
    backgroundColor: '#dcc1a7', 
    borderRadius: 10, 
    padding: 20,
    shadowColor: '#000', 
    shadowOffset: {
      width: 0,
      height: 3,
    },
    justifyContent: 'space-between',
    shadowOpacity: 0.27, 
    shadowRadius: 4.65,
    elevation: 6, 
  },
  contentList: {
    alignItems: 'stretch',
    justifyContent: 'center',
    width: '90%',
    flex: 1,
  },
  iphoneBottom: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 20, 
    backgroundColor: 'black',
  },
  containerQuestions: {
    marginTop: 20,
    marginBottom: 20,
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
  },
  crashButton: {
    position: 'absolute',
    top: 40,
    backgroundColor: '#F7E9E3', 
    borderColor: '#72665A', 
    borderWidth: 1, 
    borderRadius: 8, 
    shadowColor: '#000', 
    shadowOffset: { width: 0, height: 2 }, 
    shadowOpacity: 0.25, 
    shadowRadius: 4, 
    elevation: 5, 
    width: '80%', 
    alignItems: 'center',
    justifyContent: 'center',
    height: 80,
  },
  bottomButton: {
    position: 'absolute',
    bottom: 0,
    backgroundColor: '#72665A',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    height: 50,
  },
  button: {
    marginTop: 10,
    backgroundColor: '#72665A', 
    borderRadius: 4,
    paddingVertical: 12,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#5c5249', 
    shadowOffset: { width: 0, height: 2 }, 
    shadowOpacity: 0.25, 
    shadowRadius: 4, 
    elevation: 3, 
  },
  buttonDisabled: {
    marginTop: 10,
    backgroundColor: 'rgba(114,	102,	90, 0.5)', 
    borderRadius: 4,
    paddingVertical: 12,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',

  },
  buttonMenu: {
    width: '80%',
    height: 50,
    backgroundColor: '#72665A',
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    margin: 20,
    shadowColor: '#5c5249',
    shadowOffset: { width: 2, height: 5 },
    shadowOpacity: 0.25,
    shadowRadius: 3,
    elevation: 4,
  },
  gradeButton: {
    padding: 10,
    backgroundColor: '#72665A',
    borderRadius: 5,
  },
  gradeButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 20,
  },
  symptomText: {
    fontSize: 30,
    textAlign: 'center',
  },
  welcomeText: {
    fontSize: 20,
    marginBottom: 20,
  },
  questionContainer: {
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 50,
    flex:1,
  },
  savedButtonContainer: {
    flex: 3,
    alignSelf: 'flex-end',
    marginRight: 20,
    marginBottom: 20,
    marginTop: 20,
  },
  saveButton: {
    position: 'absolute',
    bottom: 90,
    backgroundColor: '#72665A', 
    borderRadius: 4,
    paddingVertical: 12,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#5c5249', 
    shadowOffset: { width: 0, height: 2 }, 
    shadowOpacity: 0.25, 
    shadowRadius: 4, 
    elevation: 3, // Android elevation for shadow
  },
  commentInput: {
    borderWidth: 1,
    borderColor: 'grey',
    borderRadius: 5,
    padding: 5,
    backgroundColor: '#F7E9E3',
    height: 150,
    textAlignVertical: 'top',
    fontSize: 16,
  },
  commentActivityInput: {
    borderWidth: 1,
    borderColor: 'grey',
    borderRadius: 5,
    padding: 5,
    backgroundColor: '#F7E9E3',
    height: 80,
    textAlignVertical: 'top',
    width: '80%',
    fontSize: 16,
  },
  durationInput: {
    borderColor: 'gray',
    backgroundColor: '#F7E9E3',
    borderWidth: 1,
    borderRadius: 5,
    height: 30,
    textAlignVertical: 'center',
    textAlign: 'center',
    fontSize: 20,
  },
  buttonRow: {
    flexDirection: 'row',
    marginTop: 20,
    justifyContent: 'space-between',
    marginBottom: 20,
    width: '80%',
  },
  hasCrashed: {
    backgroundColor: '#8B0000', // Change background color to red
  },
  crashButtonText: {
    fontSize: 40, 
    color: '#000'
  },
  buttonText: {
    fontSize: 20, 
    color: '#F7E9E3',
  },
  bottomButtonText:{
    color: '#F7E9E3',
    fontSize: 17,
    fontWeight: '300',
  },
  bgFill: {
    position: 'absolute',
    top: 0,
    left: 0,
    borderRadius: 7, // Match border radius
  },

  rectangle: {
    backgroundColor: 'rgba(0, 0, 0, 0.1)',
    padding: 20,
    borderRadius: 10,
  },

  text: {
    fontSize: 16,
    color: '#000',
    textAlign: 'left',
  },
  buttonGradeContainer: {
    flexDirection: 'row',
    justifyContent: 'center', 
    marginTop: 20, 
  },
  progressContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    justifySelf: 'flex-start',
    paddingBottom: 10,
  },
  dot: {
    borderRadius: 50,
    marginHorizontal: 5,
  },
  activityContainer: {
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#72665A',
  },
  activityText: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 5,
  },
  activityTitleText: {
    fontSize: 20,
    marginBottom: 5,
    marginTop: 10,
    textAlign: 'left',
  },
  durationText: {
    fontSize: 18,
  },
  commentText: {
    marginTop: 5,
    fontSize: 16,
    marginRight: '7%',
  },
  commentContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  iconContainer: {
    marginTop: 5,
    alignSelf: 'flex-end',
    marginLeft: 'auto',
  },
  addButton: {
    marginTop: 10,
    marginBottom: 70,
    margin: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addButtonContainer: {
    alignItems: 'center',
  },
  iconButtonContainer: {
    position: 'absolute',
    top: 0,
    right: 20,
    zIndex: 1,
  },
  iconSendContainer: {
    position: 'absolute',
    top: 0,
    right: 60,
    zIndex: 1,
  },
  listText: {
    fontSize: 20,
  },
  
});
  
export default styles;
